services:
  kit-api.nginx:
    container_name: kit-api.nginx
    networks:
      - kit-api-net
    ports:
      - "${NGINX_PORT}:80"
    image: nginx:stable-alpine
    volumes:
      - ../app:/app
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - kit-api.php
    restart: unless-stopped

  kit-api.php:
    container_name: kit-api.php
    networks:
      - kit-api-net
    working_dir: /app
    environment:
      - TZ=Europe/Moscow
    build:
      dockerfile: ./php/Dockerfile
      context: ./
    volumes:
      - ../app:/app
    depends_on:
      - kit-api.db
      - kit-api.memcached
    restart: unless-stopped

  kit-api.db:
    container_name: kit-api.db
    networks:
      - kit-api-net
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  kit-api.memcached:
    container_name: kit-api.memcached
    image: memcached:latest
    restart: unless-stopped

networks:
  kit-api-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
